[package]
name = "miscellaneous"
version = "0.1.0"
edition = "2024"


[dependencies]
dxlink = { path = "../.." }
tokio = { version = "1.28.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"